### ISSUE TITLE
giving warning about the usage of life cycle method componentWillUpdate

### ISSUE THREAD

**Issue by venkat77777** [abbasmoosavi/react-native-best-viewpager#3]
Below is the warning message I'm getting when running my app.

> Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: IndicatorViewPager

**Comment by venkat77777** [comment]
Any update on this issue?

**Comment by RiatIO** [comment]
@abbasmoosavi  - Please address this.

**Comment by RiatIO** [comment]
@abbasmoosavi  - Just change it to **shouldComponentUpdate** instead of componentWillUpdate

**Comment by abbasmoosavi** [comment]
> @abbasmoosavi - Just change it to **shouldComponentUpdate** instead of componentWillUpdate

Thank you dear
